config/routes.rb
Rails.application.routes.draw do
  get '/' => 'landing#index'

  resources :customers

  resources :customers do
    resources :followups
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :followups, dependent: :destroy
  validates :name, :contact_info, { presence: true }
end

app/models/followup.rb
class Followup < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/followups_controller.rb
class FollowupsController < ApplicationController

  def create
    @customer = Customer.find(params[:customer_id])
    @followup = @customer.followups.create(followup_params)

    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @followup = @customer.followups.find(params[:id])
    @followup.destroy
    redirect_to customer_path(@customer)
  end

  private
  def followup_params
    params.require(:followup).permit(:comments)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    get_customer_from_params
  end

  def new
    @customer = Customer.new
  end

  def edit
    get_customer_from_params
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def update
    get_customer_from_params

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'new'
    end
  end

  def destroy
    get_customer_from_params.destroy

    redirect_to customers_path
  end

  private
  def get_customer_from_params
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :contact_info)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>

  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> kept this customer from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :contact_info %>
    <%= f.text_field :contact_info %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/customers/edit.html.erb
<%= render 'form' %>

app/views/customers/index.html.erb
<%= link_to "Add New Customer", new_customer_path %>
<table>
    <tr>
      <td><h3>Company Name</h3></td>
      <td><h3>Address</h3></td>
    </tr>
  <% @customers.each do |customer| %>
    <tr>
      <td><p><%= link_to "#{customer.name}", customer_path(customer) %></p></td>
      <td><p><%= customer.contact_info %></p></td>
      <td><p><%= link_to 'Edit', edit_customer_path(customer) %></p></td>
      <td><p><%= link_to 'Delete', customer_path(customer),
                                    method: :delete,
                                    data: {confirm: "confirm delete of #{customer.name}"} %></p></td>
    </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
<h1> ADD A CUSTOMER </h1>

<%= render 'form' %>

<%= link_to "Go Back", customers_path %>

app/views/customers/show.html.erb
<h1> Customer Data</h1>
<p><%= @customer.name %></p>
<p><%= @customer.contact_info %></p>

<% if @customer.followups.any? %>
  <h4> follow ups </h4>
  <%= render @customer.followups %>
<% end %>

<h4> add a follow up note: </h4>
<%= render 'followups/form' %>

<%= link_to "Edit", edit_customer_path(@customer) %>

<%= link_to 'Delete', customer_path(@customer),
                                    method: :delete,
                                    data: {confirm: "confirm delete of #{@customer.name}"} %>

<%= link_to "Back to Customer List", customers_path %>

app/views/followups/_followup.html.erb
<p>
  <em>comment:</em> <%= followup.comments %>
</p>

<p>
  <em>date:</em> <%= time_ago_in_words(followup.created_at) %>
</p>

<%= link_to "Delete", [followup.customer, followup],
                      method: :delete,
                      data: { confirm: 'delete this follow up?'} %>

app/views/followups/_form.html.erb
<%= form_for([@customer, @customer.followups.build]) do |f| %>
  <p>
    <%= f.text_field :comments %>
  </p>
  <p>
    <%= f.submit "Add a follow up" %>
  </p>
<% end %>

app/views/landing/index.html.erb
<h1> welcome to bob's CRM </h1>
<%= link_to "View Customer Data", controller: 'customers' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>